### ISSUE TITLE
[BUG] Failure to load magics (e.g., %status or %%graph_notebook_config)

### ISSUE THREAD

**Issue by brianhy** [aws/graph-notebook#117]
**Describe the bug**

Ran through graph-notebook walkthrough and would receive failures running magics like %status or %%graph_notebook_config.  Error was `UsageError: Line magic function `%status` not found.`

**To Reproduce**
1. Follow steps on readme but use poetry to isolate your install
2. Only install exactly what's specified
3. Load notebook `01-About-the-Neptune-Notebook` and run the `%status` cell.

**Expected behavior**
Status invokes and succeeds/fails based on graph server setup

**Desktop (please complete the following information):**
 - OS: Mac Big Sur 11.2.3 (M1 arm64)
 - Terminal running in rosetta
 - Versions
     - graph-notebook 2.1.1
     - python 3.8

**Additional context**
Actual failure appears to be because boto3 is not in setup.py.

Debugged things by:
```
poetry run python
Python 3.8.7 (default, Feb 25 2021, 09:33:46)
[Clang 12.0.0 (clang-1200.0.32.29)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from graph_notebook.magic import load_ipython_extension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'graph_notebook.magic'
>>> from graph_notebook.magics import load_ipython_extension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brianhyams/Library/Caches/pypoetry/virtualenvs/neptune-jupyter-8Y5wcRJs-py3.8/lib/python3.8/site-packages/graph_notebook/magics/__init__.py", line 7, in <module>
    from .graph_magic import Graph
  File "/Users/brianhyams/Library/Caches/pypoetry/virtualenvs/neptune-jupyter-8Y5wcRJs-py3.8/lib/python3.8/site-packages/graph_notebook/magics/graph_magic.py", line 26, in <module>
    from graph_notebook.configuration.generate_config import generate_default_config, DEFAULT_CONFIG_LOCATION, AuthModeEnum, \
  File "/Users/brianhyams/Library/Caches/pypoetry/virtualenvs/neptune-jupyter-8Y5wcRJs-py3.8/lib/python3.8/site-packages/graph_notebook/configuration/generate_config.py", line 11, in <module>
    from graph_notebook.neptune.client import SPARQL_ACTION
  File "/Users/brianhyams/Library/Caches/pypoetry/virtualenvs/neptune-jupyter-8Y5wcRJs-py3.8/lib/python3.8/site-packages/graph_notebook/neptune/client.py", line 11, in <module>
    from boto3 import Session
ModuleNotFoundError: No module named 'boto3'
```

Adding boto3 to my local poetry dependencies fixes this.

**Comment by austinkline** [comment]
Thanks @brianhy for the bug report! Looks like botocore is the dependency we have, but we've missed boto3. We should be able to include this fix in our next release.

**Comment by austinkline** [comment]
This issue should now be resolved with our latest release. Please let us know if you run into any other issues!
