### ISSUE TITLE
[BUG] ImportError: cannot import name 'soft_unicode' from 'markupsafe'

### ISSUE THREAD

**Issue by bendinah** [aws/graph-notebook#267]
**Describe the bug**
When following the setup steps, I'm getting this error:
```
ImportError: cannot import name 'soft_unicode' from 'markupsafe'
```
when I get this [this step](https://github.com/aws/graph-notebook/blob/9b9a67f42c5601f539015c91568e557ede96bab6/README.md?plain=1#L109):

```
jupyter nbextension install --py --sys-prefix graph_notebook.widgets
```

**To Reproduce**
1. Go to a clean machine (without graph-notebook or its dependencies installed)
2. Follow steps one by one in setup documentation
3. Run the `jupyter nbextension install --py --sys-prefix graph_notebook.widgets` step

**Expected behavior**
A simple, flawless installation, of course!

**Screenshots**
```
C:\Users\dave>jupyter nbextension install --py --sys-prefix graph_notebook.widgets
Traceback (most recent call last):
  File "c:\users\dave\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dave\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\dave\AppData\Local\Programs\Python\Python39\Scripts\jupyter-nbextension.EXE\__main__.py", line 7, in <module>
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\jupyter_core\application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\traitlets\config\application.py", line 846, in launch_instance
    app.start()
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\notebook\nbextensions.py", line 980, in start
    super().start()
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\jupyter_core\application.py", line 253, in start
    self.subapp.start()
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\notebook\nbextensions.py", line 708, in start
    self.install_extensions()
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\notebook\nbextensions.py", line 679, in install_extensions
    full_dests = install(self.extra_args[0],
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\notebook\nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\notebook\nbextensions.py", line 1114, in _get_nbextension_metadata
    m = import_item(module)
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\traitlets\utils\importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\graph_notebook\widgets\__init__.py", line 9, in <module>
    from .force import Force  # noqa F401
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\graph_notebook\widgets\force\__init__.py", line 6, in <module>
    from .force_widget import Force  # noqa F401
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\graph_notebook\widgets\force\force_widget.py", line 6, in <module>
    from graph_notebook.network.EventfulNetwork import EventfulNetwork
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\graph_notebook\network\__init__.py", line 6, in <module>
    from .sparql import SPARQLNetwork  # noqa F401
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\graph_notebook\network\sparql\__init__.py", line 6, in <module>
    from .SPARQLNetwork import SPARQLNetwork  # noqa F401
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\graph_notebook\network\sparql\SPARQLNetwork.py", line 10, in <module>
    from graph_notebook.network.EventfulNetwork import EventfulNetwork, DEFAULT_GRP
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\graph_notebook\network\EventfulNetwork.py", line 13, in <module>
    from graph_notebook.decorators.decorators import check_if_dict_access_regex, get_variable_injection_dict_and_indices
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\graph_notebook\decorators\decorators.py", line 13, in <module>
    from graph_notebook.visualization.template_retriever import retrieve_template
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\graph_notebook\visualization\template_retriever.py", line 8, in <module>
    from jinja2 import Template
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\jinja2\__init__.py", line 12, in <module>
    from .environment import Environment
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\jinja2\environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\jinja2\defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\jinja2\filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (c:\users\dave\appdata\local\programs\python\python39\lib\site-packages\markupsafe\__init__.py)

```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 98.0.4758.102 (Official Build) (64-bit)

**Additional context**
This may be related to recent change(s) in dependent Python module(s) that has prompted issues in related AWS github projects:

https://github.com/aws/aws-sam-cli/issues/3661

**Comment by michaelnchin** [comment]
Hi @bendinah, thank you for the bug report!

I was able to reproduce the same error on a fresh Python 3.9.7 environment with graph-notebook v3.1.1, following the installation steps in the README. As suggested, the root cause is a [breaking change](https://github.com/pallets/markupsafe/pull/261) introduced with `markupsafe==2.1.0`.

We will pin `markupsafe<2.1.0` in `requirements.txt` to ensure that a compatible version of the package is installed during setup; this change will go out with our next release. Until then, please run `pip install markupsafe==2.0.1` prior to installing `graph-notebook` in the setup.
