### ISSUE TITLE
Stackoverflow when loading airport dataset

### ISSUE THREAD

**Issue by brleandro** [aws/graph-notebook#312]
I got the following error when trying to load airport dataset using %seed:

ion","US-AK").property("runways",4).property("longest",11800).property("elev",439).property("country","US").property("city","Fairbanks").property("lat",64.81510162d).property("lon",-147.8560028d), aliases={g=g}}}].
java.lang.StackOverflowError
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.prepareSiteAndReceiver(CallSiteWriter.java:243)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.makeCallSite(CallSiteWriter.java:291)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCachedCall(InvocationWriter.java:352)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:442)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:150)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeInvokeMethodCall(InvocationWriter.java:124)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.writeInvokeMethod(InvocationWriter.java:509)
        at org.codehaus.groovy.classgen.AsmClassGenerator.visitMethodCallExpression(AsmClassGenerator.java:868)
        at org.codehaus.groovy.ast.expr.MethodCallExpression.visit(MethodCallExpression.java:68)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.prepareSiteAndReceiver(CallSiteWriter.java:254)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.prepareSiteAndReceiver(CallSiteWriter.java:243)
        at org.codehaus.groovy.classgen.asm.CallSiteWriter.makeCallSite(CallSiteWriter.java:291)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCachedCall(InvocationWriter.java:352)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:442)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeCall(InvocationWriter.java:150)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.makeInvokeMethodCall(InvocationWriter.java:124)
        at org.codehaus.groovy.classgen.asm.InvocationWriter.writeInvokeMethod(InvocationWriter.java:509)

 - OS: Macos M1
 - Tinkerpop image: tinkerpop/gremlin-server:3.5.3 and latest.

**Comment by michaelnchin** [comment]
Hi @brleandro,

You are likely seeing the `StackOverflowError` because the default JVM thread stack allocation for Gremlin Server is not large enough to process the airports dataset queries.

Increasing the stack size to 2MB is sufficient to resolve this. Edit `gremlin-server.sh` by adding `-Xss2m` flag to the JAVA_OPTIONS variable, then restart the Gremlin Server instance, as documented [here](https://github.com/aws/graph-notebook/tree/main/additional-databases/gremlin-server#using-seed-with-gremlin-server).

Please let us know if you have further issues/concerns after performing these steps.

**Comment by brleandro** [comment]
Thanks @michaelnchin! 

I set up the JAVA_OPTS environment variable and it worked!
